import React from "react";
import Table from "../components/atoms/Table";
import Pill from "../components/atoms/Pill";
import { storiesOf } from "@storybook/react";

const props = {
  thead: [
    { type: "normal", name: "normal" },
    { type: "fire", name: "fire" },
    { type: "water", name: "water" },
    { type: "grass", name: "grass" },
    { type: "electric", name: "electric" },
    { type: "ice", name: "ice" },
    { type: "ground", name: "ground" },
    { type: "rock", name: "rock" },
    { type: "psychic", name: "psychic" },
    { type: "ghost", name: "ghost" },
    { type: "steel", name: "steel" },
    { type: "bug", name: "bug" },
    { type: "dragon", name: "dragon" },
    { type: "fighting", name: "fighting" },
    { type: "dark", name: "dark" },
    { type: "fairy", name: "fairy" },
    { type: "poison", name: "poison" },
    { type: "flying", name: "flying" },
  ],
  tbody: [
    {
      type: "normal",
      name: "normal",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
    {
      type: "fire",
      name: "fire",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type="immune" name="0" />,
        "-",
        <Pill type="notEffective" name="1/2" />,
        <Pill type="notEffective" name="1/2" />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
    {
      type: "water",
      name: "water",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type={"x2"} name={"1/2"} />,
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
    {
      type: "grass",
      name: "grass",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type={"x2"} name={"1/2"} />,
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
    {
      type: "electric",
      name: "electric",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type={"x2"} name={"1/2"} />,
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
    {
      type: "ice",
      name: "ice",
      data: [
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        <Pill type={"notEffective"} name={"1/2"} />,
        <Pill type={"notEffective"} name={"1/2"} />,
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
      ],
    },
  ],
};

storiesOf("Atoms|Assets|Table", module).add("Table", () => (
  <Table {...props} />
));
